# Generated by Django 4.0.4 on 2022-05-16 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_alter_note_pub_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Note',
        ),
    ]
